AunctionAppMVC/Controllers/AuctionController.cs
using AunctionApp.BLL.Interfaces;
using AunctionApp.BLL.Models;
using AunctionApp.BLL.Pagination;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AunctionAppMVC.Controllers
{
    [Route("[controller]/[action]/{productId?}")]
    public class AuctionController : Controller
    {
        private readonly IProductService _ProductService;
        private readonly IUserService _UserService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public AuctionController(IProductService productService, IUserService userService, IHttpContextAccessor httpContextAccessor)
        {
            _ProductService = productService;
            _UserService = userService;
            _httpContextAccessor = httpContextAccessor;
        }


        public async Task<IActionResult> GetAuction(string productId)
        {
            var model = await _ProductService.GetAuction(productId);
            return View(model);
        }


        [Authorize(Roles = "User")]
        public async Task<IActionResult> MakeBid(string productId)
        {
            var bidder = _httpContextAccessor.HttpContext?.User.FindFirstValue(ClaimTypes.Name);
            return View(new AddOrUpdateBidVM { ProductId = productId, Bidder = bidder });
        }


        [Authorize]
        public async Task<IActionResult> Home(int pg=1)
        {
            var model = await _ProductService.GetAuctionsWithBidsAsync();
            var count = model.Count();
            int pagesize = 3;
            if(pg < 1)
                pg= 1;

            var pager = new Pagination(count, pg, pagesize);
            var rescip = (pg - 1) * pagesize;
            var data= model.Skip(rescip).Take(pager.PageSize).ToList();   
            
            this.ViewBag.Pagination = pager;

            return View(data);
        }


        [HttpPost]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> SaveBid(AddOrUpdateBidVM model)
        {
            if (ModelState.IsValid)
            {
                var (successful, msg) = await _ProductService.AddOrUpdateAsync(model);
                if (successful)
                {

                    TempData["SuccessMsg"] = msg;
                    return RedirectToAction("Home");
                }
                TempData["ErrMsg"] = msg;
                return View("MakeBid");
            }
            return View("Home");
        }
    }
}

AunctionAppMVC/Controllers/HomeController.cs
using AunctionApp.BLL.Interfaces;
using AunctionAppMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AunctionAppMVC.Controllers
{
    
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductService _ProductService;
        public HomeController(ILogger<HomeController> logger, IProductService productService)
        {
            _logger = logger;
            _ProductService = productService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _ProductService.GetAuctions();
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AunctionAppMVC/Views/Auction/GetAuction.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

@model AunctionApp.BLL.Models.AuctionVMForm;

<section class="mt-5">
    <main id="main">
        <section id="portfolio-details" class="portfolio-details">
            <div class="container shadow-lg p-3 mb-5 bg-white rounded w-70">

                <div class="row gy-4">

                    <div class="col-lg-8">
                        <div class="portfolio-details-slider swiper">
                            <div class="swiper-wrapper align-items-center">

                                <div class="swiper-slide">
                                    <img src="~/img/Auctions/@Model.ProductImagePath" alt="">
                                </div>                      

                            </div>
                            <div class="swiper-pagination"></div>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="portfolio-info">
                            <h3>@Model.ProductName</h3>
                            <ul>
                                <li><strong>Price: </strong>$ @Model.ActualAmount</li>
                                <li><strong>Status: </strong>@Model.Status</li>                       
                            </ul>
                        </div>
                        <div class="portfolio-description">
                            <h2>Description</h2>
                            <p>
                                @Model.Description
                            </p>
                        </div>
                    </div>

                </div>

            </div>
        </section>
    </main>
</section>
@section Scripts
    {
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
 }

AunctionAppMVC/Views/Auction/Home.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";

    Pagination pager = new Pagination();
    int pageNo = 0;
    if (ViewBag.Pagination != null)
    {
        pager = ViewBag.Pagination;
        pageNo = pager.CurrentPage;
    }
}
 
@using AunctionApp.BLL.Pagination;
@using AunctionApp.DAL.Entities;
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc;
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager


@model IEnumerable<AunctionApp.BLL.Models.AuctionWithBidVM>


<section class="mt-5">
@if (@TempData["SuccessMsg"] != null)
{
    <div class="alert alert-success alert-dismissible fade show w-75 mx-auto d-block" role="alert">
        <strong>Success!</strong> @TempData["SuccessMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


@if (@TempData["ErrMsg"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show w-75 mx-auto d-block" role="alert">
        <strong>Error!</strong> @TempData["ErrMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


@foreach (var item in Model.Select((value, i) => new { value, i }))
{      
  <section id="features" class="mt-4 features">
      <div class="container shadow-lg p-3 mb-4 bg-white rounded w-95" data-aos="fade-up">

      <div class="row">
          <div class="image col-lg-6" style='background-image: url("../img/Auctions/@item.value.ProductImagePath");' data-aos="fade-right"></div>
        
        <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content" data-aos="fade-right" data-aos-delay="100">
          <h3>@item.value.ProductName</h3>

          <p class="fst-bold">
           @item.value.Description
          </p>

          <p class="fw-bold">
            PRICE: $@item.value.ActualAmount
          </p>

          <p class="fw-bold">
            STATUS: @item.value.Status
          </p>        

            @if (User.IsInRole("User"))
            {
                @if (item.value.Status != "Sold")
                {
                    <div class="d-flex"> <strong> Time Left:
                        <span id="countdown" data-ProductId="@item.value.Id"> </span>
                    </strong></div>
                     <br />

                    <span class="px-2">
                        <a asp-controller="Auction" asp-action="MakeBid" asp-route-ProductId="@item.value.Id" title="Make Bid" style="color:black">
                            Make Bid: 
                            <i class="fa-sharp fa-solid fa-plus fa-2xl" style="color:green"></i>
                        </a>
                    </span>
                }
                else
                {                      
                    <div id="ClosedcountdownElement"></div>
                    <p class="fw-bold">
                        Sold To: @item?.value?.Bids?.Max(u=> u.Bidder) for:  $@item?.value?.Bids?.Max(u=> u.BidPrice)
                    </p>
                }
            }

            else
            {
                @if (item.value.Status == "Sold")
                {
                    <div id="ClosedcountdownElement"></div>
                    <p class="fw-bold">
                        Sold To: @item?.value?.Bids?.Max(u=> u.Bidder) for:  $@item?.value?.Bids?.Max(u=> u.BidPrice)
                    </p>
                }
               
            }

            @if (item?.value.Status != "Sold")
            {
                <div class="mx-5 mt-4">
                    <div class="col-lg-6 order-2 order-lg-3" >
                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Bidder</th>
                                    <th scope="col">Bid Time</th>
                                    <th scope="col">($)Bid Price</th>

                                </tr>
                            </thead>

                            <tbody>
                            @foreach (var bid in item.value.Bids.Select((value, i) => new { value, i }))
                            {
                                <tr>
                                    <th scope="row">@(
                                    bid.i + 1
                                    )</th>
                                    <td>@bid.value.Bidder</td>
                                    <td>@bid.value.BidTime </td>
                                    <td>@bid.value.BidPrice</td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>     
                </div>
            }
            </div>
      </div>
    </div>

  </section>
  }
    <div class=" container data-aos-delay=" 100"">
        @if(pager.TotalPages > 0)
        {
            <ul class="pagination">

                @if (pager.CurrentPage > 1)
                {
                    <li>
                        <a class="" asp-controller="Auction" asp-action="Home" asp-route-pg="1" style="color:green">
                            First
                        </a>
                    </li>

                    <li>
                        <a class="" asp-controller="Auction" asp-action="Home" asp-route-pg="@(pager.CurrentPage - 1)" style="color:red">
                            Previous
                        </a>
                    </li>
                }

                @for(var pge = pager.StartingPage; pge <= pager.EndingPage; pge++)
                {
                    <li>
                        <a class="@(pge == pager.CurrentPage? "active":"")" asp-controller="Auction" asp-action="Home" asp-route-pg="@pge">
                            @pge
                        </a>
                    </li>
                }
                
                @if(pager.CurrentPage < pager.TotalPages)
                {
                    <li>
                        <a class="" asp-controller="Auction" asp-action="Home" asp-route-pg="@(pager.CurrentPage + 1)" style="color:green">
                        Next
                        </a>
                    </li>

                    <li>
                        <a class="" asp-controller="Auction" asp-action="Home" asp-route-pg="@(pager.CurrentPage - 1)" style="color:red">
                        Last
                        </a>
                    </li>
                }
            </ul>
        }
    </div>
</section>

@section Scripts
    {
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
 }

AunctionAppMVC/Views/Auction/MakeBid.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

@model AunctionApp.BLL.Models.AddOrUpdateBidVM

@using AunctionApp.DAL.Entities;
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc;
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager



<section class="mt-3">

@if (@TempData["SuccessMsg"] != null)
{
    <div class="alert alert-success alert-dismissible fade show w-75" role="alert">
        <strong>Success!</strong> @TempData["SuccessMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


@if (@TempData["ErrMsg"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show w-75" role="alert">
        <strong>Error!</strong> @TempData["ErrMsg"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<main id="main">
        <div class="container mt-6">

            <section class="section register min-vh-80 d-flex flex-column align-items-center justify-content-center py-4">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
                            <div class="card mb-3">

                                <div class="card-body">
                                    <div class="pt-4 pb-2">
                                        <h5 class="card-title text-center pb-0 fs-4">Place A Bid</h5>
                                    </div>
                                    @{
                                        var currentUser = User?.Identity?.Name;
                                    }
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <p>Place a bid,@currentUser</p>

                                        <form class="row g-3" asp-controller="Auction" asp-action="SaveBid" novalidate>

                                            <div class="alert-danger" asp-validation-summary="@ValidationSummary.ModelOnly"></div>
                                               
                                            <input type="hidden" class="form-control" asp-for="@Model.ProductId">
                                                                                        
                                            <input type="hidden" class="form-control" asp-for="@Model.Bidder">                             

                                            <div class="col-12">                                         
                                                    <label asp-for="@Model.BidPrice" class="form-label"></label>
                                                    <input class="form-control" asp-for="@Model.BidPrice">
                                                    <span asp-validation-for="@Model.BidPrice"></span>                                        
                                            </div>

                                            <div class="col-12">
                                                <button class="btn btn-success w-100" type="submit">Place bid</button>
                                            </div>

                                        </form>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </section>
        </div>

    </main>
</section>